### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by calvinlfer** [romix/quickser#4]
Hey @romix, would this be able to support versioning of any kind? This would be especially useful for long term event sourcing solutions especially with Akka.

**Comment by romix** [comment]
`quickser` is not further developed since a couple of years. 

I suggest you have a look at the http://github.com/romix/akka-kryo-serialization or https://github.com/EsotericSoftware/kryo instead. These projects are actively developed and could be a good match for your needs.

**Comment by calvinlfer** [comment]
Thanks @romix, I did actually try out Kryo and it is awesome but I didn't really find anything on versioning. Is there some sort of support offered by Kryo?

**Comment by romix** [comment]
You may want to look at https://github.com/EsotericSoftware/kryo#compatibility
Specifically read about `VersionFieldSerializer`, `TaggedFieldSerializer` and `CompatibleFieldSerializer`

**Comment by calvinlfer** [comment]
Thanks a lot for the help. I really appreciate it. Great work with your plugins :-)
